### ISSUE TITLE
Encoding error in feed parsed

### ISSUE THREAD

**Issue by filipesaraiva** [zzottel/feed2red#2]
Hello, first thanks for this project. I am trying to use it in order to save performance of my admin server.

I have a feed in UTF-8 encoding but the script sends the updates to RedMatrix in a wrong enconde.

The feed is http://periodico.blog.br/atom.php and the RedMatrix channel is https://red.vilarejo.pro.br/channel/periodico.

Thank you again!

**Comment by zzottel** [comment]
Hm. I wonder what is different about my German feeds with umlauts so that I never had problems there. I'll just merge your fix and look closely if it generates any problems.

Thanks!

**Comment by zzottel** [comment]
Sorry, I had to revert your pull request. The first time it ran today, it produced wrong special characters in titles in one of my feeds (which had worked correctly before). The second time it didn't work at all, dying with the error message "Cannot decode string with wide characters at /usr/lib/perl/5.14/Encode.pm line 174, <FILE> line 29."

I'll try to find out why the feed you try to post doesn't work. It seems to be valid, so I don't know what's actually wrong there. This may take some time, though.

**Comment by filipesaraiva** [comment]
Could you share your feeds with error?

**Comment by zzottel** [comment]
Not sure which one caused the abort, but the one that had errors in titles was http://www.nordbayern.de/cmlink/15.423?cid=2.232

**Comment by zzottel** [comment]
I've found this bug report about XML::Feed: https://rt.cpan.org/Public/Bug/Display.html?id=43004

Following some comments there, I set
$XML::Atom::ForceUnicode = 1;
in feed2red.pl. That fixes your feed and keeps mine ok, too.

Could you test that with your other feeds, too? If everything works, I'd push that fix here.

**Comment by zzottel** [comment]
Just for clarity:

My feed is RSS, yours is Atom. All German feeds I used seem to have been RSS feeds, or else I probably would have stumbled over the same problem myself, too.

The XML::Atom module that is used by XML::Feed provides an utf8 string which is not marked as such, i.e. for Perl internally it's not clear that this is utf8.

This can only be changed using a global Perl variable, which is why this isn't fixed in XML::Feed. We can just set this global variable in feed2red.pl, though, as we are not a module ourselves. :-)

**Comment by zzottel** [comment]
Just read the documentation for XML::Atom::Feed here: http://search.cpan.org/~miyagawa/XML-Atom-0.41/lib/XML/Atom/Feed.pm

That made clear that setting $XML::Atom::ForceUnicode = 1 is the fix we need, so I pushed that to the git without further tests now.

Should there be any further problems, please just reopen the ticket.

**Comment by filipesaraiva** [comment]
Thanks @zzottel, it is working fine with my Atom feed now!
